on:
  push:
    branches:
    - citest

name: Development
env:
    ENV: development
    IMAGE_TAG: v${{github.run_number}}-build
    SERVICE_NAME: ${{ github.event.repository.name }}
    WORK_DIR: ${{ github.workspace }}
    RO_REPO: my-tools
jobs:
  build:
    name: Build the docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./${{ env.SERVICE_NAME }}
      
      - name: Checkout tools
        uses: actions/checkout@v2
        with:
          repository: jjjjjacky/devops
          token: ${{ secrets.PAT }}
          path: ./${{ env.RO_REPO }}
          
      - name: Build Step
        run: |
              pwd
              ls ./
              echo "Echoing ${RO_REPO}"
              cd ${WORK_DIR}/${RO_REPO} && ls ./
              echo "Echoing ${SERVICE_NAME}"
              cd ${WORK_DIR}/${SERVICE_NAME} && ls ./
              
              
