on:
  push:
    branches:
    - citest

name: Development
env:
    ENV: development
    IMAGE_TAG: v${{github.run_number}}-build
    SERVICE_NAME: ${{ github.event.repository.name }}
jobs:
  build:
    name: Build the docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./{{ SERVICE_NAME }}
      
      - name: Checkout tools
        uses: actions/checkout@v2
        with:
          repository: jjjjjacky/devops
          token: ${{ secrets.PAT }}
          path: my-tools
          
      - name: Build Step
        run: |
              pwd
              ls ./
              
              
